import { useCallback } from "react";

export default function ExportPanel({ nodes, edges, meta, topic, onClose }) {

  // ── Export as JSON ─────────────────────────────────────────
  const exportJSON = useCallback(() => {
    const data = { topic, nodes: nodes.map(n => n.data), edges, meta };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = `${topic?.replace(/\s+/g, "_") || "mindmap"}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }, [nodes, edges, meta, topic]);

  // ── Export as Markdown ─────────────────────────────────────
  const exportMarkdown = useCallback(() => {
    const lines = [`# ${topic || "Mind Map"}`, ""];

    // Group nodes by depth
    const root   = nodes.find(n => n.data.type === "root");
    const branch = nodes.filter(n => n.data.type === "branch");
    const leaf   = nodes.filter(n => n.data.type === "leaf");

    if (root) lines.push(`## ${root.data.label}`, "");

    for (const b of branch) {
      lines.push(`### ${b.data.label}`);
      // Find leaves connected to this branch
      const connectedLeaves = edges
        .filter(e => e.source === b.id || e.target === b.id)
        .map(e => {
          const otherId = e.source === b.id ? e.target : e.source;
          return leaf.find(l => l.id === otherId);
        })
        .filter(Boolean);

      for (const l of connectedLeaves) {
        lines.push(`- ${l.data.label}`);
      }
      lines.push("");
    }

    // Edge relationships
    lines.push("## Relationships", "");
    for (const edge of edges) {
      const from = nodes.find(n => n.id === edge.source)?.data.label || edge.source;
      const to   = nodes.find(n => n.id === edge.target)?.data.label || edge.target;
      lines.push(`- **${from}** _${edge.label}_ **${to}**`);
    }

    if (meta?.conflicts?.length > 0) {
      lines.push("", "## Conflicts Detected", "");
      for (const c of meta.conflicts) {
        lines.push(`- ${c.edge_a} ↔ ${c.edge_b}`);
        lines.push(`  > ${c.reason}`, "");
      }
    }

    lines.push("", `---`, `_Generated by MindGraph · ${new Date().toLocaleDateString()}_`);

    const blob = new Blob([lines.join("\n")], { type: "text/markdown" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = `${topic?.replace(/\s+/g, "_") || "mindmap"}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [nodes, edges, meta, topic]);

  // ── Export as PNG ──────────────────────────────────────────
  const exportPNG = useCallback(() => {
    const flowEl = document.querySelector(".react-flow__renderer");
    if (!flowEl) return;

    import("https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js")
      .then(mod => {
        const html2canvas = mod.default || window.html2canvas;
        html2canvas(flowEl, {
          backgroundColor: "#08080f",
          scale: 2,
          useCORS: true,
          logging: false,
        }).then(canvas => {
          const url = canvas.toDataURL("image/png");
          const a   = document.createElement("a");
          a.href     = url;
          a.download = `${topic?.replace(/\s+/g, "_") || "mindmap"}.png`;
          a.click();
        });
      })
      .catch(() => {
        // Fallback: use built-in canvas
        const svg = document.querySelector(".react-flow__renderer svg");
        if (!svg) return;
        const blob = new Blob([svg.outerHTML], { type: "image/svg+xml" });
        const url  = URL.createObjectURL(blob);
        const a    = document.createElement("a");
        a.href     = url;
        a.download = `${topic?.replace(/\s+/g, "_") || "mindmap"}.svg`;
        a.click();
        URL.revokeObjectURL(url);
      });
  }, [topic]);

  const exports = [
    {
      id:          "json",
      label:       "JSON",
      description: "Raw graph data — nodes, edges, meta",
      icon:        "{ }",
      action:      exportJSON,
      color:       "#4ecdc4",
    },
    {
      id:          "markdown",
      label:       "Markdown",
      description: "Structured outline with relationships",
      icon:        "MD",
      action:      exportMarkdown,
      color:       "#7c6ff7",
    },
    {
      id:          "png",
      label:       "PNG / SVG",
      description: "Visual snapshot of the graph",
      icon:        "IMG",
      action:      exportPNG,
      color:       "#f7a34b",
    },
  ];

  return (
    <div style={{
      position: "absolute", inset: 0,
      background: "rgba(5,5,15,0.85)",
      backdropFilter: "blur(6px)",
      display: "flex", alignItems: "center", justifyContent: "center",
      zIndex: 1000,
    }}>
      <div style={{
        background: "#13131f",
        border: "1px solid #2a2a3e",
        borderRadius: "16px",
        padding: "32px",
        width: "420px",
        maxWidth: "90vw",
      }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "24px" }}>
          <div>
            <div style={{ fontSize: "11px", color: "#7c6ff7", letterSpacing: "2px", textTransform: "uppercase", marginBottom: "4px", fontFamily: "'DM Mono', monospace" }}>
              Export
            </div>
            <div style={{ fontSize: "20px", fontWeight: 700, color: "#fff", fontFamily: "'DM Sans', sans-serif" }}>
              {topic || "Mind Map"}
            </div>
            <div style={{ fontSize: "12px", color: "#5a5a7a", marginTop: "4px", fontFamily: "'DM Mono', monospace" }}>
              {nodes.length} nodes · {edges.length} edges
            </div>
          </div>
          <button onClick={onClose} style={{
            background: "transparent",
            border: "1px solid #2a2a3e",
            borderRadius: "8px",
            color: "#a8a8c0",
            cursor: "pointer",
            padding: "8px 14px",
            fontSize: "13px",
            fontFamily: "'DM Sans', sans-serif",
          }}>
            Close
          </button>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
          {exports.map(ex => (
            <button key={ex.id} onClick={ex.action} style={{
              display: "flex",
              alignItems: "center",
              gap: "16px",
              background: "#0d0d1a",
              border: "1px solid #2a2a3e",
              borderRadius: "10px",
              padding: "16px",
              cursor: "pointer",
              textAlign: "left",
              transition: "border-color 0.15s",
              width: "100%",
            }}
              onMouseEnter={e => e.currentTarget.style.borderColor = ex.color}
              onMouseLeave={e => e.currentTarget.style.borderColor = "#2a2a3e"}
            >
              <div style={{
                width: "44px", height: "44px",
                background: ex.color + "18",
                border: `1px solid ${ex.color}44`,
                borderRadius: "8px",
                display: "flex", alignItems: "center", justifyContent: "center",
                fontSize: "12px", fontWeight: 700,
                color: ex.color,
                fontFamily: "'DM Mono', monospace",
                flexShrink: 0,
              }}>
                {ex.icon}
              </div>
              <div>
                <div style={{ fontSize: "14px", fontWeight: 600, color: "#e8e8f0", fontFamily: "'DM Sans', sans-serif", marginBottom: "2px" }}>
                  {ex.label}
                </div>
                <div style={{ fontSize: "12px", color: "#5a5a7a", fontFamily: "'DM Sans', sans-serif" }}>
                  {ex.description}
                </div>
              </div>
              <div style={{ marginLeft: "auto", color: "#2a2a3e", fontSize: "18px" }}>→</div>
            </button>
          ))}
        </div>

        <div style={{ marginTop: "20px", padding: "12px", background: "#0d0d1a", borderRadius: "8px", border: "1px solid #1e1e30" }}>
          <div style={{ fontSize: "11px", color: "#5a5a7a", fontFamily: "'DM Mono', monospace", lineHeight: 1.6 }}>
            Generated {new Date().toLocaleDateString()} · MindGraph v4.0 · {meta?.agent_version || "v2.0"} · {meta?.pipeline || "3-agent-chain"}
          </div>
        </div>
      </div>
    </div>
  );
}
